### ISSUE TITLE
The issue with the inputs and labels for organizing event

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/distributed_minispace#234]
![image](https://github.com/SaintAngeLs/distributed_minispace/assets/96334335/298d062e-be49-417d-bdd8-eae3d117827f)

there is an issue with labels alignment In FireFox browser.

**Comment by an2508374** [comment]
Now, this issue should be fixed in branch "frontend_admin_update". Names of textboxes always will be above places to type some value, even if value is empty.

![Screenshot from 2024-05-31 21-16-49](https://github.com/SaintAngeLs/distributed_minispace/assets/148250180/29df600f-075e-4f64-ac33-4e80feff5507)

**Comment by an2508374** [comment]
I've made a typo in last commit name, there should be (#243).
